name: Deploy kiosk update

on:
  release:
    types: [released]

jobs:
  deploy-kiosk-update:
    if: startsWith(github.ref, 'refs/tags/app-v')

    runs-on: ubuntu-latest

    steps:
      - name: Set Info
        id: info
        run: |
          echo "::set-output name=bundle_name::${GITHUB_REPOSITORY##*/}-app-${GITHUB_REF##*/*-}.tar.gz"
          echo "::set-output name=bundle_version::${GITHUB_REF##*/*-}"

      - name: Download Release Bundle
        uses: dsaltares/fetch-gh-release-asset@0.0.5
        with:
          token: ${{ secrets.RADBOT_GITHUB_API_TOKEN }}
          version: tags/app-${{ steps.info.outputs.bundle_version }}
          file: test.txt

      - name: Deploy release
        run: |
           echo "Deploying release to firebase:" 
           cat test.txt